

List<String> States= [
  'Arunachal Pradesh',
  'Bihar',
  'Goa',
  'Gujarat',
  'Jammu and Kashmir',
  'Jharkhand',
  'West Bengal',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Orissa',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Tripura',
  'Uttaranchal',
  'Uttar Pradesh',
  'Haryana',
  'Himachal Pradesh',
  'Chhattisgarh',
  'Andaman and Nicobar',
  'Pondicherry',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Chandigarh',
  'Lakshadweep',
];